package io.github.pgatzka.videogen.ui;

import com.vaadin.flow.component.html.H2;
import com.vaadin.flow.component.html.H3;
import com.vaadin.flow.component.html.Paragraph;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;
import com.vaadin.flow.router.Route;

@Route("terms")
public class TermsOfServiceView extends VerticalLayout {

  public TermsOfServiceView() {
    setPadding(true);
    setSpacing(true);
    setMaxWidth("800px");
    getStyle().set("margin", "0 auto");

    add(new H2("Terms of Service"));
    add(new Paragraph("Last updated: 2026-04-08"));

    add(new H3("1. Service Description"));
    add(
        new Paragraph(
            "Sorting Algorithms Visualized is a web application that generates "
                + "video visualizations of sorting algorithms. The application may "
                + "automatically publish generated videos to TikTok on behalf of the "
                + "authorized account."));

    add(new H3("2. TikTok Integration"));
    add(
        new Paragraph(
            "This application uses the TikTok Content Posting API to upload and publish "
                + "videos to TikTok. By authorizing this application, you grant it permission "
                + "to upload videos to your TikTok account. You can revoke this access at any "
                + "time through your TikTok account settings."));

    add(new H3("3. Content"));
    add(
        new Paragraph(
            "All videos generated by this application are algorithmic visualizations "
                + "of sorting algorithms. Videos contain no user-generated content, personal "
                + "data, or copyrighted material. Generated videos may include auto-generated "
                + "captions and hashtags."));

    add(new H3("4. Data Collection"));
    add(
        new Paragraph(
            "This application stores TikTok OAuth tokens required for API access, "
                + "video metadata (view counts, likes, comments, shares) retrieved from "
                + "the TikTok API, and video generation job configuration. No personal "
                + "user data beyond TikTok API tokens is collected or stored."));

    add(new H3("5. Disclaimer"));
    add(
        new Paragraph(
            "This application is provided as-is without warranty. The developer is not "
                + "responsible for any content posted to TikTok through this application or "
                + "any consequences arising from its use."));

    add(new H3("6. Contact"));
    add(new Paragraph("For questions, contact the application administrator."));
  }
}
