ALTER TABLE video_job ADD COLUMN glow_effect BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE video_job ADD COLUMN particle_trail BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE video_job ADD COLUMN tweening BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE video_job ADD COLUMN speed_run BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE video_job ADD COLUMN second_algorithm VARCHAR(50);
